modLoader="kotlinforforge"
loaderVersion="[4.10,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/unyielding-items/issues"

[[mods]]
    modId="unyielding_items"
    version="1.0"
    displayName="Unyielding Items"
	authors="ManApart"
    description='''
   Items never break
    '''
    credits="Items never break"

[[dependencies.unyielding_items]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.unyielding_items]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1)"
    ordering="NONE"
    side="BOTH"
